dist: xenial
language: python
sudo: required
before_install:
- sudo apt-get update && sudo apt-get install librdkit-dev python-rdkit 
python:
- 2.7
install:
- sudo pip install requests bs4 numpy cython
script:
- python setup.py install 
- echo $PYTHONPATH
- python -m auto_martini test
