sudo: false
language: python
python:
- 3.6
install:
- pip install requests bs4 numpy cython
addons:
 apt:
 source:
 - boost-latest
 packages:
 - libboost-dev
script:
- python setup.py install && cd .. && python -m auto_martini test
