dist: xenial
sudo: true
language: python
python:
- 3.6-dev
install:
- pip install requests bs4 numpy cython
addons:
 apt:
  update: true
  packages:
  - libboost-python-dev
  - libboost-all-dev
script:
- python setup.py install && cd .. && python -m auto_martini test
