sudo: true
language: python
python:
- 2.7
install:
- sudo apt-get install python-rdkit && pip install requests bs4 numpy cython
script:
- python setup.py install && cd .. && python -m auto_martini test
