version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:

      - checkout # checkout src code to working dir

      - run:
          name: install dependencies
          command: |
            pip3 install requests bs4 numpy cython cmake --user

      - run:
          python3 setup.py install --user

      - run:
          name: run tests
          command: |
            python3 -m auto_martini test

      - store_test_results:
          path: test-results
