version: 2
jobs:
  build:

    docker:
      - image: circleci/python:3.6.4 

    working_directory: ~/repo

    steps:

      - checkout # checkout src code to working dir

      - run:
         name: update env vars
         command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
         name: install global dependencies
         command: |
	    sudo sed -i '/jessie-backports/d' /etc/apt/sources.list sudo sed -i '/jessie-updates/d' /etc/apt/sources.list ZZ
            sudo apt-get update && sudo apt-get install libboost-all-dev libboost-python-dev

      - run:
          name: install local dependencies
          command: |
            pip3 install requests bs4 numpy cython cmake --user

      - run:
          python3 setup.py install --user

      - run:
          name: run tests
          command: |
            python3 -m auto_martini test

      - store_test_results:
          path: test-results
